name = "LSODA"
uuid = "7f56f5a3-f504-529b-bc02-0b1fe5e64312"
authors = ["Romain Veltz and Chris Rackauckas"]
version = "0.5.0"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
DiffEqBase = "5"
julia = "1"

[extras]
DiffEqProblemLibrary = "a077e3f3-b75c-5d7f-a0c6-6bc4c8ec64a9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DiffEqProblemLibrary"]
